packages:
  - packages/*

# linkWorkspacePackages: true
linkWorkspacePackages: deep

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd

shamefullyHoist: false

verifyDepsBeforeRun: install
